version: "2"
checks:
  method-count:
    enabled: true
    config:
      threshold: 30
  method-lines:
    enabled: true
    config:
      threshold: 100
  file-lines:
    enabled: true
    config:
      threshold: 550

plugins:
  phpcodesniffer:
    enabled: true

  phan:
    enabled: true
    config:
      file_extensions: "php"

  phpmd:
    enabled: true

  sonar-php:
    enabled: true